# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='wind_string',
            new_name='wind_str',
        ),
    ]
